using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;

namespace CDCatalogEF
{
    /// <summary>
    /// UnitTestAlbum creates a unique album with a existing genre and artist
    /// and adds it to the database.  Then, it fetches and deletes it.
    /// </summary>
    [TestClass]
    public class UnitTestAlbum
    {
        public UnitTestAlbum()
        {

        }

        [TestMethod]
        public void TestAlbumAdd()
        {
            using (var ctx = new CDCatalogEntities())
            {
                //Get an artist we know exists -- Avicii
                Artist A = ctx.Artists.Where(n => n.ArtistName.ToLower().Equals("kaskade")).FirstOrDefault();
                //Get a genre we know exists -- Dance
                Genre G = ctx.Genres.Where(n => n.GenreName.ToLower().Equals("electronic")).FirstOrDefault();
                //create a test album
                Album m = new Album();
                m.AlbumID = 0; // autogenerated on add
                m.AlbumYear = 2014;
                m.ArtistID = A.ArtistID;
                m.AlbumTitle = "The KqxKAW Test Album";
                m.AlbumRating = 5;
                m.GenreID = G.GenreID;
                //add it to the context
                ctx.Albums.Add(m);
                int count = ctx.SaveChanges();
                Assert.IsTrue(count > 0 && m.AlbumID > 0, "No Record Added");
            }
        }

        [TestMethod]
        public void TestAlbumFetch()
        {
            using (var ctx = new CDCatalogEntities())
            {
                //Find the test album in the database
                Album m = ctx.Albums
                    .Where(n => n.AlbumTitle.ToLower().Equals("the kqxkaw test album"))
                    .FirstOrDefault();
                Assert.IsTrue(m != null, "No Record Found");
            }
        }

        [TestMethod]
        public void TestAlbumDelete()
        {
            using (var ctx = new CDCatalogEntities())
            {
                //find the list of "Testing Artists"
                //in case duplicates were added in the previous tests
                var list = ctx.Albums
                    .Where(n => n.AlbumTitle.ToLower().Equals("the kqxkaw test album"));

                ctx.Albums.RemoveRange(list);
                int count = ctx.SaveChanges();
                Assert.IsTrue(count > 0, "No Record Deleted");
            }
        }
    }
}
